### ISSUE TITLE
Доработки по главной странице

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#1]
- [x] ну вверху ссылки можно сразу заменить на IT-АУТСОРСИНГ ВИДЕОНАБЛЮДЕНИЕ КАРТРИДЖИ
- [x] соответственно ниже картиник тож с названиаями поменять

- [x] вверху бы еще добавить ссыолку на Контакты

**Comment by KaskaRUS** [comment]
Из-за ссылки на меню все поломалось при ресайзе

**Comment by jmscent** [comment]
надо поменять слова кадриджи на КАРТРИДЖИ))

**Comment by jmscent** [comment]
еще текст на сайте стал вроде какойто пиксельный без сглаживания , это бы исправить

**Comment by KaskaRUS** [comment]
приложи скрин

**Comment by jmscent** [comment]
надо поменять картину по видеонаблюдении на 2 пункте с 3 (где картриджи), а над картриджами повесить соответствующую

**Comment by jmscent** [comment]
и еще все  таки есть пиксельность, скрин прилгаю, на нем под цифрой 1 и 2
![default](https://user-images.githubusercontent.com/34363045/34717310-a4bb54ec-f543-11e7-97be-81e7bd17e7ce.jpg)

**Comment by jmscent** [comment]
Предлагаю сделать такой вариант: при нажатии (в шапке сайта) любой услуги\товара, будет "перепрыгивать" обзор на место страницы , где будет такой вид(смотреть картинку)
![default](https://user-images.githubusercontent.com/34363045/34915212-05cfff6a-f933-11e7-9298-ce491cd68a79.jpg)

**Comment by jmscent** [comment]
может как вариант, чтобы больше товара предложить по каталогу сделтать горизонтальную прокрутку: товар1.....товар21
