### ISSUE TITLE
Разделы сайта

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#13]
Предлагаю сделать такой вариант: при нажатии (в шапке сайта) любой услуги\товара, будет "перепрыгивать" обзор на место страницы , где будет такой вид(смотреть картинку)

может как вариант, чтобы больше товара предложить по каталогу сделтать горизонтальную прокрутку: товар1.....товар21

**Comment by jmscent** [comment]
Кидаю наполнение этих товаров/услуг

[КаталогНаполненный.xlsx](https://github.com/KaskaRUS/itservice/files/1669998/default.xlsx)

**Comment by KaskaRUS** [comment]
Добавил 3 раздела
