### ISSUE TITLE
Доработки на сайте

### ISSUE THREAD

**Issue by jmscent** [KaskaRUS/itservice#15]
Заменить текст,который написан на скрине, выделен красным

![3-](https://user-images.githubusercontent.com/34363045/35436661-53ff4436-02a0-11e8-8c0e-9451cfa72b8f.png)

**Comment by jmscent** [comment]
Думаю стоит убрать пока карту местоположения совсем  (т.к. пока не снимаю не офис не склад) и в контактах оставить только электронный адрес и телефон
![default](https://user-images.githubusercontent.com/34363045/35436773-d232942a-02a0-11e8-9e55-01cad8290e8e.png)

**Comment by jmscent** [comment]
Нужно сделать так, чтобы при нажатии на изображение логотипа и надписи переходило в начальное состояние сайта (при открытии сайта по умолчанию)

![default](https://user-images.githubusercontent.com/34363045/35440250-9d968e06-02af-11e8-8fd5-5325028fd83c.png)

**Comment by jmscent** [comment]
сделать отправку сообщений с сайта
![default](https://user-images.githubusercontent.com/34363045/35456472-9f82e020-02e6-11e8-9f0c-1994890a2216.png)

**Comment by KaskaRUS** [comment]
![image](https://user-images.githubusercontent.com/3288986/36247379-e1eb1276-1244-11e8-9be6-c9d0834f6239.png)
