### ISSUE TITLE
Настроить поведение при ресайзе

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#2]
![it - opera_018](https://user-images.githubusercontent.com/3288986/33742149-12a353c4-dbb8-11e7-9cc3-3c586dee5c19.png)
 
Поведение такое:
Если окно широкое, то все норм - оставляем как есть.
Если меню начинает не влазить, то убираем сначало только номер.
Когда еще уменьшается больше, убираем все меню в гамбургер и возвращаем номер

**Comment by jmscent** [comment]
ну через телефон я смотрел сайт вродеб нормально открывалось, лесенкой

**Comment by KaskaRUS** [comment]
там проблемы при переходном состоянии

**Comment by KaskaRUS** [comment]
Готово
