### ISSUE TITLE
Сдвиг картинки сайта

### ISSUE THREAD

**Issue by jmscent** [KaskaRUS/itservice#25]
Предлагаю както сдвинуть картинку под №1 и №2 вниз, чтобы не урезалась надпись Аутсорсинг, проверял на всех браузерах такое
![default](https://user-images.githubusercontent.com/34363045/36668574-c42e3274-1b02-11e8-8a4e-b7751e0d1221.jpg)

**Comment by KaskaRUS** [comment]
Надо под каждое разрешение подстраиваться?

**Comment by jmscent** [comment]
у тебя нормально? и какое у тебя разрешение?

**Comment by KaskaRUS** [comment]
13
