### ISSUE TITLE
Про контакты

### ISSUE THREAD

**Issue by jmscent** [KaskaRUS/itservice#28]
Сделать так, чтобы при нажатиии номета телефона через мобильно приложение производился набор номера, а при нажатии с компьютера была связь с каким либо приложением типа вайбера, скайп, тьелеграм. также чтобы выходил набор номера.

**Comment by KaskaRUS** [comment]
на телефоне можно сделать
на декстопе нет

**Comment by jmscent** [comment]
ок давай тогда для телефона сделаем, там только савм номер телефона не видно вверху в мобильной версии , если только в контакты зайдешь

**Comment by KaskaRUS** [comment]
там и не куда
