### ISSUE TITLE
Придумать логотип

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#3]
Сделать несколько набросков

**Comment by jmscent** [comment]
я вот не дизайнер ... с этим плоха,лучше бы ты кинул пару вариантов а  я бы выбрал), логтип должен отражать суть компании это комплекс предоставляемых услуг

**Comment by jmscent** [comment]
![logo1](https://user-images.githubusercontent.com/34363045/33803826-ebe1335c-dda9-11e7-90ac-147d029d6587.png)
![logo2](https://user-images.githubusercontent.com/34363045/33803827-ec01d92c-dda9-11e7-9eb5-21a2b6c1d9e1.png)
![logo3](https://user-images.githubusercontent.com/34363045/33803828-ec21faa4-dda9-11e7-9cd2-a8f26a4aa709.png)

**Comment by jmscent** [comment]
![logo4](https://user-images.githubusercontent.com/34363045/33803844-48ad5ef8-ddaa-11e7-9dc5-68aa06bca6d2.png)

**Comment by jmscent** [comment]
![logo5](https://user-images.githubusercontent.com/34363045/33803901-87e9112e-ddab-11e7-84cd-507c1bb6c3f4.png)
![logo6](https://user-images.githubusercontent.com/34363045/33803902-880f343a-ddab-11e7-9bab-4936681a9b2b.png)
![logo7](https://user-images.githubusercontent.com/34363045/33803903-8830e76a-ddab-11e7-8563-03c05f0ec010.png)
![logo8](https://user-images.githubusercontent.com/34363045/33803904-8853db76-ddab-11e7-9ff1-b79682be3eb5.png)
![logo9](https://user-images.githubusercontent.com/34363045/33803905-8879bf08-ddab-11e7-8ae3-8a2a9b0cfb9a.png)
![logo10](https://user-images.githubusercontent.com/34363045/33803906-88a29f22-ddab-11e7-894b-06666fabfd44.png)
