### ISSUE TITLE
Заменить текст про клиентов

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#7]
БОЛЬШЕ 40 БЛАГОДАРНЫХ КЛИЕНТОВ . КАЧЕСТВО РАБОТЫ – ВСЕГДА НА ВЫСОТЕ!
Придумай что тут написать

**Comment by jmscent** [comment]
я думаю убрать вобщем пока эту инфу, просто сплошным цветом заполнить элемент

**Comment by KaskaRUS** [comment]
Почему? Это гораздо повышает доверие к тебе. Я бы не стал исключать этот пункт - Один из ключевых

**Comment by jmscent** [comment]
ммм...ну я могу пока только 5 фирм вспомнить

**Comment by KaskaRUS** [comment]
Отлично

**Comment by jmscent** [comment]
ок, сначала согласую с ними

**Comment by jmscent** [comment]
думаю написать так:  БЛАГОДАРНЫЕ  КЛИЕНТЫ-НАША ЦЕЛЬ! КАЧЕСТВО РАБОТЫ – ВСЕГДА НА ВЫСОТЕ!

**Comment by KaskaRUS** [comment]
Изменил на сайте
