### ISSUE TITLE
Вспомнить всех своих клиентов

### ISSUE THREAD

**Issue by KaskaRUS** [KaskaRUS/itservice#8]
Составить список всех клиентов, найти желательно на них ссылки.

**Comment by jmscent** [comment]
Магазины Сент - scent.ru, Завод Орбита -  sporbita.ru, магазины Эдем - edemcosmetics.ru, магазины Вестерн (без сайта), магазин Матвей (без сайта), ООО "Иста-ремонт", магазин и завод Центр Стекла и Зеркал - centr-stekla-i-zerkal.ru, ООО "Кировавтогаз"  - kirovavtogaz.ru... Пока все что помню

**Comment by jmscent** [comment]
ЖКХ Кстинино http://www.gkh-kstinino.ru/

**Comment by KaskaRUS** [comment]
![image](https://user-images.githubusercontent.com/3288986/34064110-a34f42e8-e207-11e7-967d-4e1f48a928cc.png)
![image](https://user-images.githubusercontent.com/3288986/34064131-cbb741ea-e207-11e7-8e9d-a707a43ab609.png)
![image](https://user-images.githubusercontent.com/3288986/34064150-ef0c9974-e207-11e7-9892-82d0e62149a1.png)
![image](https://user-images.githubusercontent.com/3288986/34064160-0835c75e-e208-11e7-94f3-b1ae19a33534.png)
![image](https://user-images.githubusercontent.com/3288986/34064180-309e71be-e208-11e7-80d5-ed92a53800a8.png)

**Comment by jmscent** [comment]
ок

**Comment by KaskaRUS** [comment]
Добавил на страницу
